name: OasisEss
version: ${project.version}
main: top.oasismc.OasisEss
api-version: 1.18
load: POSTWORLD
softdepend: [ PlaceholderAPI, Vault, LuckPerms ]
authors: [ ChiyodaXiaoYi, StringStream_ ]
description: A essential Minecraft-Server Plugin developed by OasisGroup
permissions:
  oasis.admin:
    default: op
  oasis.perm.keep:
    default: op
  oasis.user.rename:
    default: op
commands:
  keepInventory:
    aliases:
      - ki
  oasis:
    description: /oasis reload|info
    permission: oasis.admin
  reg:
    description: /reg
  verify:
    description: /verify
    aliases:
      - yz
  login:
    aliases:
      - l
  hat:
    description: /hat
  shutdown:
    permission: oasis.admin